### ISSUE TITLE
test failures

### ISSUE THREAD

**Issue by djencks** [asciidoctor/jekyll-asciidoc#239]
When run first, these two tests fail consistently.  Otherwise they tend to pass. The seed value seems to be system dependent: I need a different value from the Travis run.

```
Randomized with seed 786
FF/Users/david/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:221: warning: method redefined; discarding old ext
.................................................................................................................................

Failures:

  1) Jekyll::AsciiDoc site with include relative to root should resolve include relative to root when base_dir is not set
     Failure/Error: (expect ::File).to exist out_file
       expected File to exist
     # ./spec/jekyll-asciidoc_spec.rb:1126:in `block (3 levels) in <top (required)>'

  2) Jekyll::AsciiDoc site with include relative to root should not set base_dir if base_dir config key has no value
     Failure/Error: (expect (site.config['asciidoctor'].key? :base_dir)).to be false
     
     NoMethodError:
       undefined method `key?' for nil:NilClass
     # ./spec/jekyll-asciidoc_spec.rb:1120:in `block (3 levels) in <top (required)>'

Finished in 2.18 seconds (files took 0.42434 seconds to load)
131 examples, 2 failures

Failed examples:

rspec ./spec/jekyll-asciidoc_spec.rb:1123 # Jekyll::AsciiDoc site with include relative to root should resolve include relative to root when base_dir is not set
rspec ./spec/jekyll-asciidoc_spec.rb:1119 # Jekyll::AsciiDoc site with include relative to root should not set base_dir if base_dir config key has no value

Randomized with seed 786
```

**Comment by djencks** [comment]
The problem was that the _config.yml was not in the root of the fixture.
The tests pass when they are not the first tests to run because jekyll-asciidoc is not completely reinitialized on each test: it remembers that it has been configured previously, although the content of the previous configuration is removed (I think).

The tests check that the configuration doesn't include `base_dir`, and this is also the case when there is no _config.yml at all.

I moved the _config.yml to the correct location and added a check that each fixture does indeed have a _config.yml at the root.
